modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="stevemaycry"
version="1.0.0"
displayName="SteveMayCry"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="efkrdnz, MCreator"

[[dependencies.stevemaycry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.stevemaycry]]
    modId="world_edit"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stevemaycry]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stevemaycry]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stevemaycry]]
    modId="structure_gel_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stevemaycry]]
    modId="huge_structure_blocks"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

